### ISSUE TITLE
[Client] Handle inline OneOf schemas

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-openapi#465]
**Description:**
$subject
```
                oneOf:
                  - properties:
                      email_notification:
                        properties:
                          alternative_host_reminder:
                            description: Notify the alternative host who is set or removed.
                            type: boolean
                          cancel_meeting_reminder:
                            description: Notify host and participants when the meeting is cancelled.
                            type: boolean                          
                      type: object
                  - properties:
                      audio_type:
                        description: Determine how participants can join the audio portion of the
                          meeting.
                        type: boolean
```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
