### ISSUE TITLE
Issue on path param generation 

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-openapi#504]
**Description:**
Typo issue in generated path param leads to compile error.
![image](https://user-images.githubusercontent.com/19235998/129514831-e68cca72-7d9c-4153-9ebb-7a0b40bf4b33.png)
Refer to the piece of code from openApi.yml
```
"/users/{user_id}/following/{follow_user_id}":
    delete:
      operationId: unfollow_user
      parameters:
        - description: The ID of the following user.
          in: path
          name: follow_user_id
          required: true
          schema:
            example: 3766357
            type: number
        - description: The ID of the user.
          in: path
          name: user_id
          required: true
          schema:
            example: 152184
            type: number
```

### OS, DB, other environment details and versions:
JDK 11
Ballerina Beta 2
Ubuntu 20.04

**Steps to reproduce:**
1. Generate the code using this [OpenApi YAML file.](https://github.com/SkNuwanTissera/ballerinax-openapi-connectors/blob/vimeo/openapi/vimeo/openapi.yml)
2. You the following command on generating the code (with tags)
```
bal openapi -i openapi.yml --mode client --tags "API Information","Albums\Album videos","Albums\Custom album logos","Albums\Custom album thumbnails","Albums\Essentials","Authentication Extras\Essentials","Categories\Channels","Categories\Groups","Categories\Subscriptions","Categories\Videos","Channels\Categories","Channels\Essentials","Channels\Moderators","Channels\Private channel members","Channels\Subscriptions and subscribers","Channels\Tags","Channels\Videos","Likes\Essentials","Portfolios\Essentials","Portfolios\Videos","Projects\Essentials","Projects\Videos","Tags\Essentials","Users\Essentials","Users\Feed","Users\Follows","Users\Internal","Users\Pictures","Users\Watch History","Videos\Comments","Videos\Content Ratings","Videos\Creative Commons","Videos\Credits","Videos\Embed Privacy","Videos\Essentials","Videos\Languages","Videos\Recommendations","Videos\Tags","Videos\Text Tracks","Videos\Thumbnails","Videos\Upload","Videos\Versions","Watch Later Queue\Essentials" --license ~/Documents/license.txt
```
3. Run the ballerina project using `bal run`
