### ISSUE TITLE
Support Enums in connector generation

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-openapi#622]
**Description:**
The `enum` keyword is used to restrict a value to a fixed set of values. It must be an array with at least one element, where each element is unique. 
```
...
JqlQueryClauseTimePredicate:
      required:
        - operator
      type: object
      properties:
        operator:
          type: string
          description: The operator between the field and the operand.
          enum:
            - before
            - after
            - from
            - to
            - 'on'
            - during
            - by
```
Related PR https://github.com/ballerina-platform/ballerina-openapi/pull/363

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by aneeshafedo** [comment]
We had a discussion to find out the most suitable way to generate enums. Find the meeting notes [here](https://docs.google.com/document/d/1LVzzLNj-I9jTllejVHR5FPwacdknUiNFvDJVNVKZhJc/edit?usp=sharing). 

Sample OpenAPI

```yaml
  schema:
    default: live
    enum:
      - scheduled
      - live
      - upcoming
    type: string
```
### Solution 1
```bal
type Meeting record {
   "live"|"upcoming"|"scheduled" meetingType;
}
```

### Solution 2
```bal
type MeetingType "live"|"upcoming"|"scheduled";

type Meeting record {
    MeetingType meetingType;
}
```

### Solution 3

```bal
const LIVE = "live";
const UPCOMING = "upcoming";
const SCHEDULED = "scheduled";
const RECURRING = "recurring";

type MeetingType LIVE|UPCOMING|SCHEDULED;

type Meeting record {
    MeetingType meetingType;
};

type WebinarType RECURRING|SCHEDULED;

type Webinar record {
    WebinarType webinarType;
};
```

What would be the most suitable solution out of above three ? @hevayo @indikasampath2000 @hasithaa @NipunaRanasinghe @MaryamZi

**Comment by NipunaRanasinghe** [comment]
@aneeshafedo option 3 seems to be the better option in terms of clarity, but it may lead to redeclared constants issues (incase there will be enum entries with same name in different enums)
That being said, I prefer option 2 over option 1 (having inline union types might not be scalable when for a large set of enum entries)

**Comment by aneeshafedo** [comment]
> @aneeshafedo option 3 seems to be the better option in terms of the clarity, but IINM it may lead to redeclared constants issues (incase there will be enum entries with same name in different enums) That being said, I prefer option 2 over option 1 (having inline union types might not be scalable when for a large set of enum entries)

Yes option 3 would be the best since it also increase the usability of the client/service by providing suggestions for users when entering values for an enum. The other 2 options will only validate the value provided. 

We can achieve option 3 by checking the duplicates in the constant list before adding one. But it would be a expensive task when the number of constants is high.

**Comment by aneeshafedo** [comment]
Few of the challenges that we will face are

1. Enums can have many members
Ex: 
https://github.com/ballerina-platform/openapi-connectors/blob/c452566df018fed9fd043fa6ed65a3a606420a81/openapi/adp.paystatements/openapi.yml#L267

2. Same enum is repeated across the openapi 
Ex: 
https://github.com/ballerina-platform/openapi-connectors/blob/c452566df018fed9fd043fa6ed65a3a606420a81/openapi/apple.appstore/openapi.yaml#L18737

3. Can be in any type 
4. Need to support nullable enums 
5. Need to support reusable enums

**Comment by aneeshafedo** [comment]
After a discussion with @NipunaRanasinghe & @lnash94 decided to provide enum support using above mention both option 1 and option 2 based on the enum definition. 

### Use case 1 : Defined schema with enum values ([Reusable enums](https://swagger.io/docs/specification/data-models/enums/#:~:text=not%20enough%20here.-,Reusable%20enums,-In%20OpenAPI%203.0))

```yaml
MeetingType:
      type: string
      default: live
      enum:
        - "scheduled"
        - "live"
        - "upcoming"
    MeetingObject:
      properties:
        topic:
          description: Meeting topic.
          type: string
        type:
          description: "The meeting types. Scheduled, live or upcoming"
          $ref: "#/components/schemas/MeetingType"
      type: object
```

**Proposed code generation**

```bal
public type MeetingType "scheduled"|"live"|"upcoming";

public type MeetingObject record {
    # Meeting topic.
    string topic?;
    # The meeting types. Scheduled, live or upcoming.
    MeetingType 'type?;
};
```

This approach will be used in any place where reusable enum is defined (schema or parameter)

### Use case 2 : Inline enum in schema property

```yaml
MeetingObject:
  properties:
    topic:
      description: Meeting topic.
      type: string
    type:
      description: "Meeting Type: 1 - Instant meeting. 2 - Scheduled meeting. 3 - Recurring meeting with no fixed time. 8 - Recurring meeting with fixed time."
      enum:
        - 1
        - 2
        - 3
        - 8
      type: integer
  type: object
```

**Proposed code generation**

```bal
public type MeetingObject record {
    # Meeting topic.
    string topic?;
    # Meeting Type: 1 - Instant meeting. 2 - Scheduled meeting. 3 - Recurring meeting with no fixed time. 8 - Recurring meeting with fixed time.
    1|2|3|8 'type?;
};
```

### Use case 3 : Inline enum in parameter

```yaml
parameters:
        - description: "The meeting types. Scheduled, live or upcoming"
          in: query
          name: type
          schema:
            default: live
            enum:
              - scheduled
              - live
              - upcoming
            type: string
```

**Proposed code generation**

```bal
    resource isolated function get users/meetings("scheduled"|"live"|"upcoming" 'type = "live") returns MeetingList|error {
        string resourcePath = string `/users/meetings`;
        map<anydata> queryParam = {"type": 'type};
        resourcePath = resourcePath + check getPathForQueryParam(queryParam);
        MeetingList response = check self.clientEp->get(resourcePath);
        return response;
    }
```
@NipunaRanasinghe @lnash94 please convey any suggestions.
