### ISSUE TITLE
Ballerina `error` to `500` mapping

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-openapi#653]
I think we need to improve the current mapping to something as the below, At the moment there is not content details

```yaml
"500":
          description: Found unexpected output
          content: 
            text/plain:
              schema:
                type: string  
```
